<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../BerlinCadastre.Domain/BerlinCadastre.Domain.csproj" />
    <ProjectReference Include="../BerlinCadastre.Application/BerlinCadastre.Application.csproj" />
    <ProjectReference Include="../BerlinCadastre.Infrastructure/BerlinCadastre.Infrastructure.csproj" />
    <ProjectReference Include="../BerlinCadastre.Semantics/BerlinCadastre.Semantics.csproj" />
  </ItemGroup>
</Project>
