<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../BerlinCadastre.Domain/BerlinCadastre.Domain.csproj" />
    <PackageReference Include="dotNetRdf.Core" />
    <PackageReference Include="dotNetRdf.Shacl" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
